"""initial schema

Revision ID: 1982efdf2376
Revises: 
Create Date: 2026-08-29 00:35:07.239936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1982efdf2376'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('question_revision', sa.Integer(), nullable=False),
    sa.Column('daily_task_item_id', sa.Integer(), nullable=True),
    sa.Column('attempt_type', sa.String(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('self_assessed_mastery_state', sa.String(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('final_result_json', sa.Text(), nullable=True),
    sa.Column('final_score_source', sa.String(), nullable=True),
    sa.Column('client_request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('review_applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_task_item_id'], ['daily_task_item.id'], ),
    sa.ForeignKeyConstraint(['question_id', 'question_revision'], ['question_version.question_id', 'question_version.revision'], name='fk_attempt_question_version'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_request_id', name='uq_attempt_client_request_id')
    )
    op.create_index('ix_attempt_created_at', 'attempt', ['created_at'], unique=False)
    op.create_index('ix_attempt_finalized_at', 'attempt', ['finalized_at'], unique=False)
    op.create_index('ix_attempt_question_id', 'attempt', ['question_id'], unique=False)
    op.create_index('ix_attempt_status', 'attempt', ['status'], unique=False)
    op.create_table('daily_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('new_question_target', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_date', name='uq_daily_task_task_date')
    )
    op.create_table('daily_task_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_task_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('question_revision', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('due_date_snapshot', sa.Date(), nullable=True),
    sa.Column('completed_attempt_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['completed_attempt_id'], ['attempt.id'], ),
    sa.ForeignKeyConstraint(['daily_task_id'], ['daily_task.id'], ),
    sa.ForeignKeyConstraint(['question_id', 'question_revision'], ['question_version.question_id', 'question_version.revision'], name='fk_daily_task_item_question_version'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_task_id', 'question_id', name='uq_daily_task_item_task_question')
    )
    op.create_index('ix_daily_task_item_daily_task_id', 'daily_task_item', ['daily_task_id'], unique=False)
    op.create_index('ix_daily_task_item_question_id', 'daily_task_item', ['question_id'], unique=False)
    op.create_table('knowledge_point',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_assessment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt_knowledge_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('earned_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempt_knowledge_result_attempt_id', 'attempt_knowledge_result', ['attempt_id'], unique=False)
    op.create_index('ix_attempt_knowledge_result_knowledge_point_id', 'attempt_knowledge_result', ['knowledge_point_id'], unique=False)
    op.create_table('knowledge_card',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('knowledge_point_id', sa.String(), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_point.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_point_id')
    )
    op.create_table('question',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('primary_knowledge_point_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='ck_question_difficulty'),
    sa.ForeignKeyConstraint(['primary_knowledge_point_id'], ['knowledge_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_is_active', 'question', ['is_active'], unique=False)
    op.create_index('ix_question_primary_knowledge_point_id', 'question', ['primary_knowledge_point_id'], unique=False)
    op.create_index('ix_question_question_type', 'question', ['question_type'], unique=False)
    op.create_table('knowledge_card_progress',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('first_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['knowledge_card.id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('knowledge_card_version',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['knowledge_card.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'revision')
    )
    op.create_table('question_preference',
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('wrong_book_mode', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('question_related_knowledge_point',
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('knowledge_point_id', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_point.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'knowledge_point_id')
    )
    op.create_table('question_version',
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'revision')
    )
    op.create_table('review_state',
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('mastery_state', sa.String(), nullable=False),
    sa.Column('last_attempt_id', sa.Integer(), nullable=True),
    sa.Column('last_review_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_successes', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('algorithm_state_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['last_attempt_id'], ['attempt.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index('ix_review_state_mastery_state', 'review_state', ['mastery_state'], unique=False)
    op.create_index('ix_review_state_next_review_date', 'review_state', ['next_review_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_state_next_review_date', table_name='review_state')
    op.drop_index('ix_review_state_mastery_state', table_name='review_state')
    op.drop_table('review_state')
    op.drop_table('question_version')
    op.drop_table('question_related_knowledge_point')
    op.drop_table('question_preference')
    op.drop_table('knowledge_card_version')
    op.drop_table('knowledge_card_progress')
    op.drop_index('ix_question_question_type', table_name='question')
    op.drop_index('ix_question_primary_knowledge_point_id', table_name='question')
    op.drop_index('ix_question_is_active', table_name='question')
    op.drop_table('question')
    op.drop_table('knowledge_card')
    op.drop_index('ix_attempt_knowledge_result_knowledge_point_id', table_name='attempt_knowledge_result')
    op.drop_index('ix_attempt_knowledge_result_attempt_id', table_name='attempt_knowledge_result')
    op.drop_table('attempt_knowledge_result')
    op.drop_table('ai_assessment')
    op.drop_table('knowledge_point')
    op.drop_index('ix_daily_task_item_question_id', table_name='daily_task_item')
    op.drop_index('ix_daily_task_item_daily_task_id', table_name='daily_task_item')
    op.drop_table('daily_task_item')
    op.drop_table('daily_task')
    op.drop_index('ix_attempt_status', table_name='attempt')
    op.drop_index('ix_attempt_question_id', table_name='attempt')
    op.drop_index('ix_attempt_finalized_at', table_name='attempt')
    op.drop_index('ix_attempt_created_at', table_name='attempt')
    op.drop_table('attempt')
    op.drop_table('app_setting')
    # ### end Alembic commands ###